---
- hosts: 127.0.0.1
  connection: local
  vars:
    home: /home/krzystof
  become: yes
  become_method: sudo
  tasks:

  - include: tasks/tools.yml
  - include: tasks/zsh.yml
  - include: tasks/theme.yml
  - include: tasks/fonts.yml

  - include: tasks/node.yml

  - stat: path={{ home }}/Dropbox
    register: dropbox_dir

  - include: tasks/sublime.yml
    when: dropbox_dir.stat.exists

  - include: tasks/utils_and_fun.yml
    when: dropbox_dir.stat.exists
