---
- hosts: 127.0.0.1
  vars:
    home: /home/krzystof
  become: yes
  become_method: sudo
  tasks:

  - include: tasks/node.yml
    static: no

  # - name: get dropbox
  #   get_url: url=https://www.dropbox.com/download?plat=lnx.x86_64 dest=~/Downloads/dropbox-installer
  # untar?
  # ~/.dropbox-dist/dropboxd

  - name: get general packages
    apt: name={{ item }} update_cache=yes state=latest
    with_items:
      - zsh
      - vim

  - name: install Prezto
    git:
      repo: https://github.com/sorin-ionescu/prezto.git
      dest: /home/krzystof/.zprezto
      force: yes

  - name: have my customized theme in Prezto
    copy:
      src: ollie-theme
      dest: /home/krzystof/.zprezto/modules/prompt/functions/prompt_ollie_setup

  - name: set default shell to zsh
    command: chsh -s /bin/zsh

  - name: Copy dotfiles
    file:
      src: "/home/krzystof/Dotfiles/files/{{ item }}"
      dest: "/home/krzystof/.{{ item }}"
      state: link
    with_items:
      - vimrc
      - zlogin
      - zlogout
      - zpreztorc
      - zprofile
      - zshenv
      - zshrc
      - tmux.conf

  # - name: clone Vundle repo
  #   become_user: krzystof
  #   git:
  #     repo: https://github.com/VundleVim/Vundle.vim.git
  #     dest: /home/krzystof/.vim/bundle/Vundle.vim

