---
- hosts: 127.0.0.1
  connection: local
  vars:
    home: /home/krzystof
  become: yes
  become_method: sudo
  tasks:
  # - include: tasks/tools.yml
  # - include: tasks/dropbox.yml
  # - include: tasks/sublime.yml
  # - include: tasks/node.yml
  # - include: tasks/zsh.yml
  - include: tasks/theme.yml
