---
# Install Docker Engine and docker-compose
- name: DOCKER ~> add key
  apt_key: url="https://apt.dockerproject.org/gpg" state=present id=58118E89F3A912897C070ADBF76221572C52609D

- name: DOCKER ~> add repo
  apt_repository: repo="deb https://apt.dockerproject.org/repo/ ubuntu-{{ ansible_lsb.codename }} main" state=present

- name: DOCKER ~> install engine
  apt: name=docker-engine update_cache=yes state=present

- name: DOCKER ~> create group
  group: name=docker state=present

- name: DOCKER ~> append group to my user
  user: name={{ username }} append=yes groups=docker

- name: DOCKER ~> start docker engine on boot
  command: systemctl enable docker

- name: DOCKER ~> put docker-compose binary in the path
  get_url:
    url: https://github.com/docker/compose/releases/download/1.11.2/docker-compose-linux-x86_64
    dest: /usr/local/bin/docker-compose
    mode: "a+x"

- name: DOCKER ~> install completion script
  become_user: "{{ username }}"
  get_url: url=https://github.com/docker/compose/releases/download/1.11.2/docker-compose-linux-x86_64 dest={{ home }}/.zsh/completion/_docker-compose

