---
# Install node and yarn
- get_url:
    url: https://deb.nodesource.com/setup_6.x
    dest: "{{ home }}/Downloads"
    mode: a+x
  register: node_installer

- command: /bin/bash "{{ home }}"/Downloads/setup_6.x
  when: node_installer.changed

- apt_key: url=https://dl.yarnpkg.com/debian/pubkey.gpg state=present

- apt_repository: repo="deb https://dl.yarnpkg.com/debian/ stable main" state=present

- apt: name={{ item }} update_cache=yes state=latest
  with_items:
    - nodejs
    - yarn
