---
- name: APT | get general packages
  apt: name={{ item }} update_cache=no state=present
  with_items:
    - zsh
    - vim
    - tmux
    - terminator

- name: DOTFILES | link dotfiles
  file:
    src: "{{ home }}/Dotfiles/files/{{ item }}"
    dest: "{{ home }}/.{{ item }}"
    state: link
  with_items:
    - vimrc
    - zlogin
    - zlogout
    - zpreztorc
    - zprofile
    - zshenv
    - zshrc
    - tmux.conf

- name: VIM | clone Vundle repo
  become_user: krzystof
  git:
    repo: https://github.com/VundleVim/Vundle.vim.git
    dest: "{{ home }}/.vim/bundle/Vundle.vim"

- name: VIM | change vundle owner
  file:
    name: "{{ home }}/.vim/bundle/Vundle.vim"
    owner: krzystof
    group: krzystof
    state: directory

- name: VIM | create the colors dir
  file:
    name: "{{ home }}/.vim/colors"
    owner: krzystof
    group: krzystof
    state: directory

- name: VIM | copy my vim theme
  copy:
    src: obsidian.vim
    dest: "{{ home }}/.vim/colors/obsidian.vim"

- name: VIM | symlink my vim plugins
  file:
    src: "{{ home }}/Dotfiles/files/plugins.vim"
    dest: "{{ home }}/.vim/plugins.vim"
    state: link

- name: TERMINAL | create the terminator config dir
  file:
    name: "{{ home }}/.config/terminator"
    owner: krzystof
    group: krzystof
    state: directory

- name: TERMINAL | copy my terminator config
  file:
    src: "{{ home }}/Dotfiles/files/terminator"
    dest: "{{ home }}/.config/terminator/config"
    state: link
