---

# - apt_repository: repo="ppa:me-davidsansome/clementine" state=absent

- apt: name=clementine state=latest

- file: 
    path: "{{ home }}/.config/Clementine"
    state: directory
    owner: krzystof
    group: krzystof

- file: src={{ home }}/Dropbox/Clementine/{{ item }} dest={{ home }}/.config/Clementine/{{ item }} state=link
  with_items:
    - albumcovers
    - Clementine.conf
    - clementine.db
