---
- name: ZSH ~> ensure directory exists
  file: path={{ home }}/Repos state=directory

- name: ZSH ~> install Prezto
  git:
    repo: https://github.com/sorin-ionescu/prezto.git
    dest: "{{ home }}/Repos/prezto"
    recursive: yes
    force: yes

- name: ZSH ~> symlink prezto
  become_user: krzystof
  file:
    src: "{{ home }}/Repos/prezto"
    dest: "{{ home }}/.zprezto"
    state: link

- name: ZSH ~> create the .zsh dir
  become_user: krzystof
  file: path="{{ home }}/.zsh" state=directory

- name: ZSH ~> create the completion dir
  file: src={{ home }}/Dotfiles/completion dest="{{ home }}/.zsh/completion" state=link

- name: Symlink my custom theme
  file: 
    src: "{{ home }}/Dotfiles/files/prompt_polly_setup" 
    dest: "{{ home }}/.zprezto/modules/prompt/functions/prompt_polly_setup" 
    state: link
