---
- name: ZSH ~> ensure directory exists
  file: path={{ home }}/Repos state=directory

- name: ZSH ~> install Prezto
  git:
    repo: https://github.com/sorin-ionescu/prezto.git
    dest: "{{ home }}/Repos/prezto"
    recursive: yes
    force: yes

- name: ZSH ~> symlink prezto
  become_user: krzystof
  file:
    src: "{{ home }}/Repos/prezto"
    dest: "{{ home }}/.prezto"
    state: link

- name: ZSH ~> set default shell to zsh
  become_user: krzystof
  command: chsh -s /bin/zsh
  when: not ansible_user_shell == "/bin/zsh"

- name: ZSH ~> create the .zsh dir
  become_user: krzystof
  file: path="{{ home }}/.zsh" state=directory

- name: ZSH ~> create the completion dir
  file: src={{ home }}/Dotfiles/completion dest="{{ home }}/.zsh/completion" state=link
