[Desktop Entry]
Name=MyVeryOwnTheme
Type=X-GNOME-Metatheme
Comment=

[X-GNOME-Metatheme]
GtkTheme=Adapta
MetacityTheme=Adapta
IconTheme=Paper
GtkColorScheme=fg_color:#4c4c4c4c4c4c,bg_color:#f2f2f1f1f0f0,text_color:#3c3c3c3c3c3c,base_color:#ffffffffffff,selected_fg_color:#ffffffffffff,selected_bg_color:#ffff53533939,tooltip_fg_color:#ffffffffffff,tooltip_bg_color:#000000000000
CursorTheme=bridge
CursorSize=32
