" General basic necessary plugins
set nocompatible                "Be iMproved, required
set backspace=indent,eol,start  "Make backspace behave well
syntax on                       "Enable syntax highlighting
filetype plugin indent on       "Enable file type detection and do language-dependent indenting.

"-----Notes
" :tn    => go to next tag result
" :tp    => go to previous tag result
" :ts    => list all tags result
" ctrl ] => go to tag definition (use ctrl ^ to go back to previous buffer)



" Source the plugins file
so ~/.vim/plugins.vim



"------General settings
syntax enable
set smartindent



"---- Gvim specific
:set guioptions-=e  "no GUI tabs
:set guioptions-=m  "remove menu bar
:set guioptions-=T  "remove toolbar
:set guioptions-=r  "remove right-hand scroll bar
:set guioptions-=L  "remove left-hand scroll bar



"------General stuff
let mapleader = ','
set number
set relativenumber

set tabstop=8
set expandtab
set softtabstop=4                        " Insert mode
set shiftwidth=4                         " Spaces when using < and >
set complete=.,w,b,u                     " Autocomplete looks through current buffer, window, loaded buffers, unloaded buffers

set wildignore+=*/tmp/*,*.so,*.swp,*.zip



" Map ctrl+s to save
:nmap <c-s> :w<CR>
:imap <c-s> <Esc>:w<CR>a




"------Visuals
colorscheme srcery
set t_CO=256                             "Use 256 colors
set laststatus=2                         "Always display the status bar
let g:airline_powerline_fonts = 0
let g:airline_theme='luna'

" For line numbers, to hide them a bit
hi LineNr ctermfg=DarkGray
hi Comment ctermfg=DarkGray



"------Search

set hlsearch             "Highlight search
set incsearch
set ignorecase



"------Splits

set splitbelow
set splitright

nmap <Leader>\| :vsp<CR>
nmap <Leader>- :sp<CR>
nmap <Leader>d :tabc<CR>                  "close a tab

nmap <C-J> <C-W><C-J>
nmap <C-K> <C-W><C-K>
nmap <C-H> <C-W><C-H>
nmap <C-L> <C-W><C-L>



"------Movements

" End of the line
" nmap ] $                          
" First non blank char
nmap [ ^




"------I dont remember...
nmap <C-V> "+gP
imap <C-V> <ESC><C-V>i
vmap <C-C> "+y





"------Leaders mappings

" Use space to enter command mode
nmap <Space> :

" Shortcut to edit the vimrc file
nmap <Leader>ev :tabedit ~/.vimrc<cr>
nmap <Leader>ep :tabedit ~/.vim/plugins.vim<cr>
nmap <Leader>es :tabedit ~/.vim/UltiSnips/

" Simple highlight removal
nmap <Leader><space> :nohlsearch<cr>

" Comma + s to save
nmap <Leader>s :w<cr>



" Search with Ack
nmap <Leader>a :Ack



" Close a tab
nmap <Leader>c :tabc<cr>




"------Plugins

"/
"/ CtrlP
"/
let g:ctrlp_custom_ignore = 'node_modules\|git'
let g:ctrlp_match_window = 'top,order:ttb,min:1,max:30,results:30'

nmap <c-R> :CtrlPBufTag<cr>
"nmap <Leader>r :CtrlPMRUFiles<cr>

" Ignore package managers huge folders
let g:ctrlp_custom_ignore = '\v[\/](\.git|\.hg|node_modules|vendor)$'



"/
"/ NERDTree
"/

"NERD tree is messing with vinegar...
let NERDTreeHijackNetrw = 0   

" Make NERD Tree easy to toggle
nmap <Leader>0 :NERDTreeToggle<cr>


"/
"/ VIM Test
"/
nmap <silent> <leader>tt :TestNearest<CR> "Run test near cursor"
nmap <silent> <leader>tT :TestFile<CR>    "Run current file, or the last test file"
nmap <silent> <leader>ta :TestSuite<CR>   "Run the whole test suite"
nmap <silent> <leader>tl :TestLast<CR>    "Run the last test"




"/
"/ Auto pairs
"/

let g:AutoPairsFlyMode = 1
let g:AutoPairsShortcutBackInsert = '<C-b>'



"/
"/ Emmet
"/
" Use ctrl-m then "," to expand emmet abbr
let g:user_emmet_leader_key='<C-m>' 



"/
"/ UltiSnips
"/
let g:UltiSnipsExpandTrigger="<C-e>"



"/
"/ Syntastic
"/

set statusline+=%#warningmsg#
set statusline+=%{SyntasticStatuslineFlag()}
set statusline+=%*

let g:syntastic_always_populate_loc_list = 1
let g:syntastic_auto_loc_list = 1
let g:syntastic_check_on_open = 1
let g:syntastic_check_on_wq = 0

" PHP
let g:syntastic_php_phpcs_args = "--standard=psr2"


" JS
let g:syntastic_javascript_checkers = ['eslint']
let g:syntastic_javascript_eslint_exe = 'eslint %'



"------Auto-Commands
augroup autosourcing
    autocmd!
    autocmd BufWritePost .vimrc source %
augroup END

