set nocompatible                        " be iMproved, required

" Source the plugins file
so ~/.vim/plugins.vim



"------General settings
"
syntax enable

set backspace=indent,eol,start
let mapleader = ','
set number

set tabstop=8
set expandtab
set softtabstop=4
set shiftwidth=4


set wildignore+=*/tmp/*,*.so,*.swp,*.zip



"------Visuals
colorscheme srcery
set t_CO=256                             "Use 256 colors
set laststatus=2                         "Always display the status bar
let g:airline_powerline_fonts = 0
let g:airline_theme='luna'



"------Search

set hlsearch             "Highlight search
set incsearch
set ignorecase



"------Splits

set splitbelow
set splitright

nmap <Leader>\| :vsp<CR>
nmap <Leader>- :sp<CR>

nmap <C-J> <C-W><C-J>
nmap <C-K> <C-W><C-K>
nmap <C-H> <C-W><C-H>
nmap <C-L> <C-W><C-L>



"------Movements

" End of the line
nmap ] $                          
" First non blank char
nmap [ ^



"------I dont remember...
nmap <C-V> "+gP
imap <C-V> <ESC><C-V>i
vmap <C-C> "+y



"------Mappings

" Shortcut to edit the vimrc file
nmap <Leader>ev :tabedit ~/.vimrc<cr>

" Simple highlight removal
nmap <Leader><space> :nohlsearch<cr>

" Comma + s to save
nmap <Leader>s :w<cr>

" Use space in normal mode to enter commands
nmap <space> :

" Close a tab
nmap <Leader>c :tabc<cr>




"------Plugins

"/
"/ CtrlP
"/
let g:ctrlp_custom_ignore = 'node_modules\|git'
let g:ctrlp_match_window = 'top,order:ttb,min:1,max:30,results:30'

nmap <c-R> :CtrlPBufTag<cr>
nmap <Leader>r :CtrlPMRUFiles<cr>

let g:ctrlp_custom_ignore = '\v[\/](\.git|\.hg|node_modules|vendor)$'

"/
"/ NERDTree
"/
" Make NERD Tree easy to toggle
let NERDTreeHijackNetrw = 0   "NERD tree is messing with vinegar...

nmap <Leader>0 :NERDTreeToggle<cr>



"------Auto-Commands
augroup autosourcing
    autocmd!
    autocmd BufWritePost .vimrc source %
augroup END



"------Cheat-Sheet
" :tabc             => close a tab
" :b1 or :b2        => go to buffer 1 or 2 etc
" ctrl w and then | => expand split
" :e .              => browse the current directory
" ctrl ^ or :bp     => previous buffer

