#
# Defines environment variables.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Ensure that a non-login, non-interactive shell has a defined environment.
if [[ "$SHLVL" -eq 1 && ! -o LOGIN && -s "${ZDOTDIR:-$HOME}/.zprofile" ]]
then
  source "${ZDOTDIR:-$HOME}/.zprofile"
fi

export BLACKFIRE_CLIENT_ID=04eec34f-a765-4ca0-9f6e-79f1819e7050
export BLACKFIRE_CLIENT_TOKEN=1c455fb6ba41b936ee177c9f50f27988194c78a8f32d4325ea65fdfe13427ace
export BLACKFIRE_SERVER_ID=e7e1ade3-995a-41c2-9350-71b8adfd873c
export BLACKFIRE_SERVER_TOKEN=c868a5301557d86d8fcf6682aac4100b1e6ba67de1af1ad0c85cebe4104e326c
