#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

#
# Customize to your needs...
#

# Solarize me
# eval `dircolors $HOME/Dropbox/Prezto/solarized`

export TERM=xterm-256color

# zstyle ':completion:*:manuals'    separate-sections true
# zstyle ':completion:*:manuals.*'  insert-sections   true
# zstyle ':completion:*:man:*'      menu yes select

source $HOME/Dropbox/Scripts/aliases.sh
source $HOME/Dropbox/Scripts/helper_functions.sh
source $HOME/Dropbox/Scripts/z.sh

fpath=(~/.zsh/completion $fpath)
autoload -Uz compinit && compinit -i



# Ctrl+Space to accept shell suggestion
bindkey '^ ' autosuggest-accept


# Run a local conf if its there
LOCAL_CONF=$HOME/.zshlocal

if [[ -e ${LOCAL_CONF} ]]; then
    source $LOCAL_CONF
fi


# Boot rbenv
eval "$(rbenv init -)"

alias gh=github

export NVM_DIR="$HOME/.nvm"


# FZF
# --files: List files that would be searched but do not search
# --no-ignore: Do not respect .gitignore, etc...
# --hidden: Search hidden files and folders
# --follow: Follow symlinks
# --glob: Additional conditions for search (in this case ignore everything in the .git/ folder)
export FZF_DEFAULT_COMMAND='rg --files --hidden --follow --glob "!.git/*"'
export FZF_CTRL_T_COMMAND="$FZF_DEFAULT_COMMAND"

# . ~/Dotfiles/files/lazynvm.sh
[ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh"  # This loads nvm

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion
