#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

#
# Customize to your needs...
#

# Solarize me
# eval `dircolors $HOME/Dropbox/Prezto/solarized`

export TERM=xterm-256color

# zstyle ':completion:*:manuals'    separate-sections true
# zstyle ':completion:*:manuals.*'  insert-sections   true
# zstyle ':completion:*:man:*'      menu yes select

# Custom scripts
source $HOME/Dropbox/Scripts/aliases.sh

# Load z
source $HOME/Dropbox/Scripts/z.sh

fpath=(~/.zsh/completion $fpath)
autoload -Uz compinit && compinit -i


# Launch tmux if you can
if [[ "$TMUX" = "" ]]; then 
    tmux
fi


# Run a local conf if its there
LOCAL_CONF=$HOME/.zshlocal

if [[ -e ${LOCAL_CONF} ]]; then
    source $LOCAL_CONF
fi


# Boot rbenv
eval "$(rbenv init -)"



# Run the sync script
# /bin/bash $HOME/Dotfiles/sync.sh

mine() {
    sudo chown -R krzystof:krzystof $1
}


export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion
